WINDOW_RESOLUTION = (800, 600)
BACKGROUND_COLOR = (0, 0, 0)
FPS = 60

ENTITY_SPEED_FADE = 0.8

PLAYER_ABS_ACCEL = 1 
PLAYER_MAX_SPEED = 5
PLAYER_SPRITE_PATH = "pics/red_square.jpg"
PLAYER_HEALTH = 100

BASE_ENEMY_ABS_ACCEL = 1
BASE_ENEMY_MAX_SPEED = 3
BASE_ENEMY_SPRITE_PATH = "pics/blue_rect.png"
BASE_ENEMY_HEALTH = 10

WEAPON_COOLDOWN = 0.1
BULLET_SPEED = 10
BULLET_DAMAGE = 1
BULLET_RANGE = 500
BULLET_SPRITE_PATH = "pics/green_square.png"

SHIELD_SPRITE_PATH = "pics/white_rect.png"
SHIELD_DISTANCE = 100
SHIELD_COOLDOWN = 0.5
SHIELD_ALPHA = 90
BULLET_REFLECTION_ACCELERATION = 2
BULLET_REFLECTION_DAMAGE_UP = 2 # multiplier for damage of reflected bullet